base_url = "https://sushiware.net"
title = "sushiware.net"
description = ""
generate_feed = true

default_language = "ja"

compile_sass = true

build_search_index = false

taxonomies = [
	{name = "tags", feed = true}
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
highlight_code = true
render_emoji = true
extra_syntaxes = ["syntaxes"]

[extra]
sns = [
	{service = "twitter", url = "https://twitter.com/sushiware"},
	{service = "github", url = "https://github.com/sushiware"},
	{service = "github", url = "https://github.com/nasjp"},
]
author = "sushiware"
