name: deploy

on: [push, workflow_dispatch]

jobs:
  check:
    strategy:
      fail-fast: true

    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushiware/zola/zola:1.4.1
    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: shalzz/zola-deploy-action@v0.15.3
        env:
          BUILD_ONLY: true
      - name: Deploy
        uses: aquiladev/ipfs-action@v0.1.1
        id: upload
        with:
          path: ./public
